### ISSUE TITLE
Unable to install from Thunderstore

### ISSUE THREAD

**Issue by Hazard15301** [NilaierMusic/EnhancedIcons#1]
When trying to install this mod from the Thunderstore website, I get "Error - Extraction failed - Invalid/unsupported compression method".

![Screenshot 2024-03-23 081654](https://github.com/NilaierMusic/EnhancedIcons/assets/26782525/6bd9af83-8ee0-46e8-9405-d71dc8e87a3d)

**Comment by BAHEK-BOP** [comment]
the same problem is caused by downloading R2modman

**Comment by NilaierMusic** [comment]
Yeah, that's probably because i've used the LZMA algorithm for compression instead of the usual Deflate one. I guess i would have to reupload the archive with the more common algorithm.

**Comment by NilaierMusic** [comment]
Okay, new version works completely fine with r2modman, so i would imagine Thunderstore app should too

**Comment by Hazard15301** [comment]
Working as expected now, thanks!
